export const BULL_MQ_PARAMETER = {
  DELAY: 1000,
  ATTEMPTS: 3,
};

export const CALENDAR_PARAMETER = {
  MONTHS_TO_DISPLAY: 5,
  NUMBER_OF_MONTHS_TO_CHECK_AVAILABILITY: 24,
  MONTH_NUMBER_FORMAT: 'MM',
};
