export const BULL_MQ_PARAMETER = {
  ATTEMPTS: 3,
  BACKOFF_TYPE: 'exponential',
  BACKOFF_DELAY: 3000,
};

export const CALENDAR_PARAMETER = {
  MONTHS_TO_DISPLAY: 5,
  NUMBER_OF_MONTHS_TO_CHECK_AVAILABILITY: 24,
};

export const WHATSAPP_PARAMETER = {
  PAGE_SIZE: 8,
};

export const DATE_PARAMETER = {
  SAFETY_INTERVAL_IN_MS: 60_000,
  DAY_NUMBER_FORMAT: 'dd',
  MONTH_NUMBER_FORMAT: 'MM',
  YEAR_NUMBER_FORMAT: 'yyyy',
  HOUR_NUMBER_FORMAT: 'HH',
  MINUTE_NUMBER_FORMAT: 'mm',
  WEEKDAY_FORMAT: 'cccc',
  HOUR_MINUTE_FORMART: 'HH:mm',
};
